The objective of this notebook is to test the functionallity of all models' estimation and prediction for every posible experiment. 

There are 5 models 
- arima (static and single)
- sarima (static and single)
- dense (static, online, single and multioutput)
- cnn (static, online, single and multioutput)
- lstm (static, online, single and multioutput)

In [31]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np 
import pandas as pd
import time
import matplotlib.pyplot as plt 
import tensorflow as tf

import os

prediction_dir = '/Users/juandavidcaicedocastro/Dropbox/01_berkeley/' \
                 '17_phd/11_Papers/02_SecondPaper/transit_demand_prediction'

os.chdir(prediction_dir)
import data
import utils
from time_measure import TicToc

In [32]:
directory = 'output'
data_directory = 'data'
aggregation = 'day'
to_drop_stations = ['(40000) cable portal tunal', '(40001) juan pablo ii','(40002) manitas', '(40003) mirador del paraiso']

settings = data.read_settings()
train, test = data.train_test_data(settings)
train = train.drop(columns= to_drop_stations)
test = test.drop(columns= to_drop_stations)

In [33]:
exog_vars = list(set(train.columns[~train.columns.str.contains("\(")]))

In [34]:
# Create a smaler dataset to test models accuracy 
exog_vars = list(set(train.columns[~train.columns.str.contains("\(")]))

# For single models 
station_single = ['(02000) cabecera autopista norte']

# For multioutput models 
stations_multi = ['(02000) cabecera autopista norte',
                  '(02001) centro comercial santa fe',
                  '(02101) toberin', 
                  '(02102) calle 161', 
                  '(02103) mazuren']

## Arima - Static and Single model

In [102]:
from models.arima import arimaClass

In [103]:
arima_ss = arimaClass(settings,station_single[0])
arima_ss.fit(train[station_single + exog_vars])
result = arima_ss.predict(test[station_single + exog_vars].head(5),
                 train_mean = 0, 
                 train_std = 1)

print ('Expected Output shape: ({},{})'.format(5,7))
print ('Output shape: {}'.format(result.shape))

INFO:root:Model for station (02000) cabecera autopista norte compleated. Time 1.44 minutes


Expected Output shape: (5,7)
Output shape: (5, 7)


In [114]:
result

array([[76745.27953149, 72960.61178246, 86543.09306286, 78347.74211219,
        63826.79820889, 71660.58630304, 75158.67296821],
       [78549.59185754, 87083.30327023, 77784.43259305, 64151.36367601,
        71149.36761547, 75853.81056137, 83278.21636381],
       [92360.33033836, 78305.39761561, 63629.61267914, 71439.68124541,
        75376.62500172, 83964.03939764, 86738.65168132],
       [78598.02635868, 63653.28763332, 71406.29830089, 75397.08150723,
        83942.13319786, 86776.14494364, 78963.2653474 ],
       [58583.27931698, 70901.6635156 , 75920.98147263, 83644.95311022,
        87234.90966512, 78305.82823453, 65245.3382123 ]])

In [117]:
np.expand_dims(result, axis=0).shape

(1, 5, 7)

In [113]:
type(a) == list

True

In [106]:
train[station_single + exog_vars]

(02000) cabecera autopista norte  year_cos  week_cos  week_sin  \
timestamp                                                                    
2015-08-01                           23912.0 -0.877995 -0.222521  0.974928   
2015-08-02                           47197.0 -0.869631 -0.900969  0.433884   
2015-08-03                          110704.0 -0.861010 -0.900969 -0.433884   
2015-08-04                          115831.0 -0.852134 -0.222521 -0.974928   
2015-08-05                          115422.0 -0.843006  0.623490 -0.781831   
...                                      ...       ...       ...       ...   
2018-07-27                           87302.0 -0.914185  0.623490  0.781831   
2018-07-28                           64229.0 -0.907078 -0.222521  0.974928   
2018-07-29                           41493.0 -0.899703 -0.900969  0.433884   
2018-07-30                           87818.0 -0.892061 -0.900969 -0.433884   
2018-07-31                           87602.0 -0.884155 -0.222521 -0.974928   

            saturday  holiday  year_sin  
timestamp                                
2015-08-01         1        0 -0.478670  
2015-08-02         0        1 -0.493702  
2015-08-03         0        0 -0.508587  
2015-08-04         0        0 -0.523323  
2015-08-05         0        0 -0.537903  
...              ...      ...       ...  
2018-07-27         0        0 -0.405297  
2018-07-28         1        0 -0.420963  
2018-07-29         0        1 -0.436503  
2018-07-30         0        0 -0.451915  
2018-07-31         0        0 -0.467193  

[1096 rows x 7 columns]

In [104]:
result

array([[76745.27953149, 72960.61178246, 86543.09306286, 78347.74211219,
        63826.79820889, 71660.58630304, 75158.67296821],
       [78549.59185754, 87083.30327023, 77784.43259305, 64151.36367601,
        71149.36761547, 75853.81056137, 83278.21636381],
       [92360.33033836, 78305.39761561, 63629.61267914, 71439.68124541,
        75376.62500172, 83964.03939764, 86738.65168132],
       [78598.02635868, 63653.28763332, 71406.29830089, 75397.08150723,
        83942.13319786, 86776.14494364, 78963.2653474 ],
       [58583.27931698, 70901.6635156 , 75920.98147263, 83644.95311022,
        87234.90966512, 78305.82823453, 65245.3382123 ]])

# Sarima - Static and Single model

In [ ]:
from models.sarima import sarimaClass

In [ ]:
sarima_ss = sarimaClass(settings,station_single[0])
sarima_ss.fit(train[station_single + exog_vars].head(100))
result = sarima_ss.predict(test[station_single + exog_vars].head(5),
                 train_mean = 0, 
                 train_std = 1)

print ('Expected Output shape: ({},{})'.format(5,7))
print ('Output shape: {}'.format(result.shape))

## Easy test for all stations

In [35]:
from models.dense import denseClass
from models.cnn import cnnClass
from models.lstm import lstmClass

In [36]:
# Settings file
TRAIN_DATE = settings['train_date']
INPUT_WIDTH = settings['steps_back']
LABEL_WIDTH = settings['forecast_window']
BATCH_SIZE = 32 #settings['batch_size']

In [37]:
def static(model, stations, test_limit = None):
    """ 
    Simulates a static time series model
    
    Parameters: 
    ------------
    - model: str. model type e.g.: 'dense', 'cnn', 'lstm'
    - stations: list. List of station(s) to model 
    - limit: int. Maximum test predictions
    
    Return: 
    - prediction array. shape:(predictions, forecast_window, stations)
    
    """
    # Add one because shifting exogenous variables will remove one
    if test_limit:
        test_limit+=1 
        
    train_df = train[stations + exog_vars]
    test_df = test[stations + exog_vars].iloc[:test_limit]
    
    normalize_data = data.min_max(train_df,
                                  test_df,
                                  stations)
    _train, _test, _min, _max = normalize_data
    
    df = pd.concat((_train, _test))
    df[exog_vars] = df[exog_vars].shift(-1)
    df = df.iloc[:-1,:]
    
    w = data.WindowGenerator(input_width=INPUT_WIDTH, 
                             label_width=LABEL_WIDTH,
                             shift=LABEL_WIDTH, 
                             batch_size=BATCH_SIZE, 
                             train_date=TRAIN_DATE,
                             label_columns=stations,
                             data=df)
    
    if model == 'dense':
        model_class = denseClass(settings)
    elif model == 'cnn':
        model_class = cnnClass(settings)
    elif model == 'lstm':
        model_class = lstmClass(settings)


    model_class.fit(w)
    results = model_class.predict(w) # Normalized prediction 
    results = data.unnormalize_min_max(results, _min, _max)
    return results


In [8]:
static('dense', station_single, test_limit = 6)[:5,-1]

array([[90592.39825881],
       [86908.50382853],
       [88782.14395726],
       [63895.36220801],
       [35326.58712971]])

In [42]:
a=static('dense', stations_multi, test_limit = 6)#[:5,-1]

In [83]:
test[stations_multi].head(6)

(02000) cabecera autopista norte  \
timestamp                                      
2018-08-01                           91465.0   
2018-08-02                           92407.0   
2018-08-03                           93127.0   
2018-08-04                           65318.0   
2018-08-05                           39997.0   
2018-08-06                           90023.0   

            (02001) centro comercial santa fe  (02101) toberin  \
timestamp                                                        
2018-08-01                            12909.0          31070.0   
2018-08-02                            13134.0          30792.0   
2018-08-03                            13976.0          30877.0   
2018-08-04                             8621.0          15906.0   
2018-08-05                             3854.0           5733.0   
2018-08-06                            12164.0          29153.0   

            (02102) calle 161  (02103) mazuren  
timestamp                                       
2018-08-01             5926.0           9708.0  
2018-08-02             6134.0           9628.0  
2018-08-03             6209.0           9986.0  
2018-08-04             3495.0           5368.0  
2018-08-05             1397.0           1776.0  
2018-08-06             5890.0           8623.0

In [93]:
a[:,:,0]

array([[ 81076.53414369,  82615.68193793,  56398.51495922,
         27367.14731999,  67645.02729887,  85542.53891444,
         80917.60614002],
       [ 83512.46048045,  55007.13888419,  23284.35229415,
         68062.65052795,  83951.7704711 ,  80491.37383151,
         80607.96343124],
       [ 54792.48696488,  22149.85618039,  64697.06200975,
         81434.40122819,  81139.24342239,  79287.42874765,
         82117.9316895 ],
       [ 27425.97363325,  74263.83978081,  89815.44998324,
         90354.59146774,  87685.25590503,  91310.56123686,
         59499.60346603],
       [ 98802.5779295 ,  96913.9590174 ,  95629.71439433,
         95456.87655389, 101329.56092632,  66866.15086013,
         36619.58290738],
       [ 82166.41315365,  81730.47913992,  81508.74037528,
         85164.46332681,  55722.35211086,  26811.63420793,
         68330.93582809]])

In [74]:
b = np.moveaxis(a, 0, -1)
c = np.moveaxis(b, 0, -1)
c.shape

(5, 6, 7)

In [98]:
d = np.moveaxis(a, 2, 0)

In [101]:
d[0,:,] == c[0,:,:]

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [94]:
c[0,:,:]

array([[ 81076.53414369,  82615.68193793,  56398.51495922,
         27367.14731999,  67645.02729887,  85542.53891444,
         80917.60614002],
       [ 83512.46048045,  55007.13888419,  23284.35229415,
         68062.65052795,  83951.7704711 ,  80491.37383151,
         80607.96343124],
       [ 54792.48696488,  22149.85618039,  64697.06200975,
         81434.40122819,  81139.24342239,  79287.42874765,
         82117.9316895 ],
       [ 27425.97363325,  74263.83978081,  89815.44998324,
         90354.59146774,  87685.25590503,  91310.56123686,
         59499.60346603],
       [ 98802.5779295 ,  96913.9590174 ,  95629.71439433,
         95456.87655389, 101329.56092632,  66866.15086013,
         36619.58290738],
       [ 82166.41315365,  81730.47913992,  81508.74037528,
         85164.46332681,  55722.35211086,  26811.63420793,
         68330.93582809]])

In [10]:
static('cnn', station_single, test_limit = 6)[:,-1]

array([[88941.78910232],
       [88628.57421756],
       [94516.9274528 ],
       [69016.26252562],
       [31577.87005241],
       [67857.65972096]])

In [11]:
static('cnn', stations_multi, test_limit = 6)[:5,-1]

array([[74170.38137364,  9416.65627366, 21014.80163342,  4589.34429491,
         7516.4436661 ],
       [75880.68240261,  9729.02192557, 21644.72128212,  4725.69349414,
         7659.77809429],
       [78549.94354498, 10296.0267632 , 21628.92414892,  4889.39098227,
         8095.03169084],
       [51299.38935447,  6275.49519226, 11533.25852159,  2399.53972709,
         3980.03115422],
       [22833.14710126,  2449.44818902,  4371.37216572,   202.81460243,
          335.73876149]])

In [12]:
static('lstm', station_single, test_limit = 6)[:5,-1]

array([[92250.60505474],
       [90159.46135485],
       [93936.74653745],
       [68895.23138511],
       [35648.02546126]])

In [13]:
static('lstm', stations_multi, test_limit = 6)[:5,-1]

array([[86352.42833555, 12269.17276573, 28993.91927713,  5852.32237184,
         9269.06356227],
       [86743.29068947, 12497.70637709, 30271.80020714,  6101.09008634,
         9517.88446271],
       [90159.27192128, 13219.53825718, 30249.80132496,  6150.88832629,
         9934.37252307],
       [56149.97134376,  8449.96057844, 17670.22072101,  3048.64914346,
         4742.6910224 ],
       [33630.22553651,  4682.61189052,  9638.59135121,  1291.37058625,
         1585.64895442]])

In [14]:
def online(model, stations, test_limit = None):
    """ 
    Simulates a online training time series model
    
    Parameters: 
    ------------
    - model: str. model type e.g.: 'dense', 'cnn', 'lstm'
    - stations: list. List of station(s) to model 
    - limit: int. Maximum test predictions
    
    Return: 
    - prediction array. shape:(predictions, forecast_window, stations)
    
    """
    # Add one because shifting exogenous variables will remove one
    # Add LABEL_WIDTH because online training will remove it. 
    if test_limit:
        test_limit = test_limit + 1 + LABEL_WIDTH
        
    train_df = train[stations + exog_vars]
    test_df = test[stations + exog_vars].iloc[:test_limit]
    
    normalized_data = data.min_max(train_df,
                                  test_df,
                                  stations)
    
    _train, _test, _min, _max = normalized_data
    
    df = pd.concat((_train, _test))
    df[exog_vars] = df[exog_vars].shift(-1)
    df = df.iloc[:-1,:]
    
    train_index = data.train_index(df, TRAIN_DATE)
    predictions = []
    for i in df.index[train_index: -LABEL_WIDTH]:
        idx_online = data.train_index(df, i)
        df_online = df[:idx_online + 1]
        
        w = data.WindowGenerator(input_width=INPUT_WIDTH, 
                                 label_width=LABEL_WIDTH,
                                 shift=LABEL_WIDTH, 
                                 batch_size=BATCH_SIZE, 
                                 train_date=i,
                                 label_columns=stations,
                                 data=df_online)
        
        if model == 'dense':
            model_class = denseClass(settings)
        elif model == 'cnn':
            model_class = cnnClass(settings)
        elif model == 'lstm':
            model_class = lstmClass(settings)

        model_class.fit(w)
        prediction = model_class.predict(w, True)
        predictions.append(prediction)
    results = np.array(predictions)
    results = data.unnormalize_min_max(results, _min, _max)
    return np.squeeze(results, axis = 1)
    

In [15]:
a = online('dense', station_single, test_limit = 13)
a[:5,-1]

array([[90957.70061111],
       [87832.52021289],
       [89214.1066314 ],
       [63494.23323089],
       [36222.88870555]])

In [16]:
b = online('dense', stations_multi, test_limit = 13)
b[:5,-1]

array([[76564.51731074, 10711.45843875, 27277.17199969,  4723.3188203 ,
         7452.54956377],
       [85288.5084908 , 11956.19811451, 29788.61346102,  5208.55539858,
         8552.44961011],
       [77426.52126133, 10930.86098313, 26564.20388216,  4682.10757059,
         7511.04262412],
       [58387.44233185,  7134.58433756, 14635.70634547,  2747.32028121,
         3831.54841971],
       [33972.08971238,  3290.28231026,  5268.09896153,   722.62846473,
          462.64707971]])

In [17]:
c = online('cnn', station_single, test_limit = 13)
c[:5,-1]

array([[89947.89111388],
       [87680.70949924],
       [97220.46254122],
       [70819.48410571],
       [28107.81991169]])

In [18]:
d = online('cnn', stations_multi, test_limit = 13)
d[:5,-1]

array([[73672.60068053,  9374.75986689, 20856.19100738,  4558.49817562,
         7540.10407186],
       [74775.99712914,  9410.25736785, 20857.54726654,  4615.50238168,
         7427.87190568],
       [74827.18140447,  9677.81596893, 20294.96658254,  4588.83257103,
         7514.55007648],
       [53412.28408802,  7011.43506607, 13025.52698272,  2514.80252171,
         4284.68280232],
       [25866.6541232 ,  2955.80954203,  5395.11731273,   443.88783502,
          755.871421  ]])

In [19]:
e = online('lstm', station_single, test_limit = 13)
e[:5,-1]

array([[91528.28806901],
       [89485.63259876],
       [93075.99420154],
       [70415.83498549],
       [84702.9151876 ]])

In [20]:
f = online('lstm', stations_multi, test_limit = 13)
f[:5,-1]

array([[92866.1018008 , 11267.47088784, 24161.9143976 ,  6287.72546828,
         9391.05251729],
       [92895.38958454, 12380.42252409, 26516.56353629,  6566.52100229,
         9708.64346075],
       [90955.10266495, 12953.35064006, 28028.84827167,  6233.19793701,
         9325.08114505],
       [64028.96023655,  7981.16055739, 13617.13081628,  3586.53339839,
         5252.27134144],
       [30969.6884868 ,  4302.71792361,  6557.17848963,  1117.67757788,
          765.60801028]])

# Creating directory

In [21]:
def create_path(path, replace = False):
    """ 
    Create path if path is not defined. 
    If replace is True, removes and create
    empty path
    """
    try:
        os.makedirs(path)
    except FileExistsError:
        if replace:
            shutil.rmtree(path)
            os.makedirs(path)

In [29]:
output_folder = 'output' #from settings
aggregation = 'day' #from settings >> Overwrite in arguments
training = 'static' # from settings >> Overwrite in arguments
output = 'single' # from settings>> Overwrite in arguments 
model = 'dense'# from settings >> Overwrite in arguments 

path = os.path.join(output_folder,
                    aggregation,
                    training,
                    output,
                    model)

In [30]:
path

'output/day/static/single/dense'

## Dense - single/static

In [ ]:
from models.dense import denseClass

In [ ]:
a,b,c,d = data.min_max_normalize(train[station_single + exog_vars], 
                       test[station_single + exog_vars].head(6),
                       station_single)

df = pd.concat((a,b))
df[exog_vars] = df[exog_vars].shift(-1)
df = df.iloc[:-1,:]

TRAIN_DATE = settings['train_date']

w = data.WindowGenerator(input_width=14, label_width=7, 
                         shift=7, data = df, label_columns=station_single, 
                         batch_size = 32, train_date=TRAIN_DATE)

In [ ]:
dense_ss = lstmClass(settings,station_single[0])
dense_ss.fit(w)
single_results = dense_ss.predict(w,
                 train_mean = 0, 
                 train_std = 1)

print ('Expected Output shape: ({},{})'.format(5,7))
print ('Output shape: {}'.format(single_results.shape))

In [ ]:
results = single_results * (d[0]-c[0]) + c[0]
results[:,-1]

## Dense - multioutput/static

In [ ]:
from models.dense import denseClass


In [ ]:
a,b,c,d = data.min_max_normalize(train[stations_multi + exog_vars], 
                                 test[stations_multi + exog_vars].head(100),
                                 stations_multi)

df = pd.concat((a,b))
TRAIN_DATE = settings['train_date']

w = data.WindowGenerator(input_width=14, label_width=7, 
                         shift=7, data = df, label_columns=stations_multi, 
                         batch_size = 32, train_date=TRAIN_DATE)

In [ ]:
dense_ss = denseClass(settings,'hola')
dense_ss.fit(w)
multi_results = dense_ss.predict(w,
                 train_mean = 0, 
                 train_std = 1)
multi_results.shape

In [ ]:
test[stations_multi + exog_vars].head(5)

In [ ]:
((multi_results * np.array(d-c)) + np.array(c))[:5,-1]

## Dense - Single/Online

In [ ]:
from models.dense import denseClass

In [ ]:
df = pd.concat((train[station_single + exog_vars], 
                test[station_single + exog_vars].head(32)))
TRAIN_DATE = settings['train_date']

In [ ]:
# idx = data.train_index(df, TRAIN_DATE)
# input_width = 14
# shift = 7
# train_df = df.iloc[:idx]
# test_df = df.iloc[idx - input_width - shift + 1:]

In [ ]:
train_index = data.train_index(df, TRAIN_DATE)
df_online = df[:train_index+1]

In [ ]:
w = data.WindowGenerator(input_width=14, label_width=7, 
                         shift=7, data = df_online, label_columns=station_single, 
                         batch_size = 32, train_date=TRAIN_DATE)

In [ ]:
train_index = data.train_index(df, TRAIN_DATE)
predictions = []
for i in df.index[train_index: -7]:
    idx_online = data.train_index(df, i)
    df_online = df[:idx_online + 1]
    w = data.WindowGenerator(input_width=14, label_width=7, shift=7, 
                             data = df_online, batch_size = 32, train_date=i,
                             label_columns=station_single)
    
    model_class = denseClass(settings, 'ha')
    model_class.fit(w)
    prediction = model_class.predict(w, 0, 1, True)
    predictions.append(prediction)
result = np.array(predictions) 

In [ ]:
result.shape

## Dense - Multioutput/Online

In [ ]:
from models.dense import denseClass

In [ ]:
df = pd.concat((train[stations_multi + exog_vars], 
                test[stations_multi + exog_vars].head(32)))
TRAIN_DATE = settings['train_date']

train_index = data.train_index(df, TRAIN_DATE)
df_online = df[:train_index+1]

In [ ]:
train_index = data.train_index(df, TRAIN_DATE)
predictions = []
for i in df.index[train_index: -7]:
    idx_online = data.train_index(df, i)
    df_online = df[:idx_online + 1]
    w = data.WindowGenerator(input_width=14, label_width=7, shift=7, 
                             data = df_online, batch_size = 32, train_date=i,
                             label_columns=stations_multi)
    
    model_class = denseClass(settings, 'ha')
    model_class.fit(w)
    prediction = model_class.predict(w, 0, 1, True)
    predictions.append(prediction)
result = np.array(predictions) 

In [ ]:
result.shape

## CNN - Dense/multioutput

In [ ]:
from models.cnn import cnnClass

df = pd.concat((train[stations_multi + exog_vars], 
                test[stations_multi + exog_vars].head(32)))
TRAIN_DATE = settings['train_date']

train_index = data.train_index(df, TRAIN_DATE)
df_online = df[:train_index+1]

train_index = data.train_index(df, TRAIN_DATE)
predictions = []
for i in df.index[train_index: -7]:
    idx_online = data.train_index(df, i)
    df_online = df[:idx_online + 1]
    w = data.WindowGenerator(input_width=14, label_width=7, shift=7, 
                             data = df_online, batch_size = 32, train_date=i,
                             label_columns=stations_multi)
    
    model_class = cnnClass(settings, 'ha')
    model_class.fit(w)
    prediction = model_class.predict(w, 0, 1, True)
    predictions.append(prediction)
result = np.array(predictions) 

## LSTM - Dense/Multioutput

In [ ]:
from models.lstm import lstmClass

df = pd.concat((train[stations_multi + exog_vars], 
                test[stations_multi + exog_vars].head(32)))
TRAIN_DATE = settings['train_date']

train_index = data.train_index(df, TRAIN_DATE)
df_online = df[:train_index+1]

train_index = data.train_index(df, TRAIN_DATE)
predictions = []
for i in df.index[train_index: -7]:
    idx_online = data.train_index(df, i)
    df_online = df[:idx_online + 1]
    w = data.WindowGenerator(input_width=14, label_width=7, shift=7, 
                             data = df_online, batch_size = 32, train_date=i,
                             label_columns=stations_multi)
    
    model_class = lstmClass(settings, 'ha')
    model_class.fit(w)
    prediction = model_class.predict(w, 0, 1, True)
    predictions.append(prediction)
result = np.array(predictions) 

## LSTM - Single/static

In [ ]:
from models.lstm import lstmClass

a,b,c,d = data.min_max_normalize(train[station_single + exog_vars], 
                       test[station_single + exog_vars].head(6),
                       station_single)

df = pd.concat((a,b))

df[exog_vars] = df[exog_vars].shift(-1)
df = df.iloc[:-1,:]

TRAIN_DATE = settings['train_date']

w = data.WindowGenerator(input_width=14, label_width=1, 
                         shift=1, data = df, label_columns=station_single, 
                         batch_size = 32, train_date=TRAIN_DATE)

In [ ]:
lstm_ss = lstmClass(settings,station_single[0])
lstm_ss.fit(w)
single_results = lstm_ss.predict(w,
                 train_mean = 0, 
                 train_std = 1)

In [ ]:
single_results * (d[0] - c[0]) + c[0]

In [ ]:
(test[station_single].head(6) - c)/(d-c)

In [ ]:
test[station_single].head(6)

In [ ]:
b * (d-c) + c

# Savig the resutls 

In [ ]:
def prediction_dict(station, prediction, time):
    """ Saves a <station_name>.json file in the path directory. 
    
    Parameters:
    ------------
    path: 'str'. Directory path to save prediction 
    station_name: 'str'. Name of the station.
    time: float. Running time in secongs 
    prediction: array-like. Prediction array of the shape (n, OUT STEPS)
    """
    dict_ = {}
    dict_['name'] = station
    dict_['time'] = time
    dict_['prediction'] = prediction.tolist()
    return dict_

In [ ]:
multi_results.shape

In [ ]:
single_results.shape

In [ ]:
single_results

In [ ]:
np.squeeze(single_results, axis=None)

In [ ]:
prediction_dict(station_single[0],single_results,2)